name: Docker Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=30s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker-compose build

    - name: Generate application key
      run: |
        docker-compose exec app php artisan key:generate

    - name: Install composer
      run: |
        docker-compose exec app composer install --no-dev --optimize-autoloader

    - name: Install NPM
      run: |
        docker-compose exec app npm install --production

    - name: Run migrations
      run: |
        docker-compose exec app php artisan migrate --force

    - name: Test if app is running
      run: |
        docker-compose up -d
        sleep 10  # Wait for the app to start
        curl --fail http://localhost:8000  # Test if the app responds

    - name: Clean up
      run: |
        docker-compose down
      
